---
- name: "Make sure fail2ban is installed"
  apt:
    pkg: "fail2ban"
    state: "latest"

- name: "Make sure the fail2ban configuration is up to date"
  template:
    src: "fail2ban.conf.j2"
    dest: "/etc/fail2ban/fail2ban.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "restart fail2ban"

- name: "Generate fail2ban jail dot local"
  template:
    src: "jail.conf.j2"
    dest: "/etc/fail2ban/jail.local"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "restart fail2ban"

- name: "Make sure fail2ban is enabled"
  service:
    name: "fail2ban"
    enabled: true
